* let var & const...
* alert confirm & prompt...
* string concatenation with back ticks & ${variable}... 
* if else conditions...
* '===' also checks the type...
* conditional operator.. #what we call turnary in java...