* let var & const...
* alert confirm & prompt...
* string concatenation with back ticks & ${variable}... 
* if else conditions...
* '===' also checks the type...
* conditional operator.. #what we call turnary in java...



* For loops... while loops... 
* Switch case statements...

* function expressions and call_back functions...

* scope of var and let...
    -> var's scope remains to the nearest function...
    -> let's scope remains to the nearest block...

    -> var can be redefined...
    -> let can not be redefined...

    -> With var... we can declare the variable even after initialisation... 
    -> With let... Above scenario would have given you an error...



* setTimeOut... Function to execute some function after some time... (once)
* setInterval... same... (on interval basis)


